# Generated by Django 5.2.9 on 2025-12-27 04:10

import campuskeyapi.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("adminapp", "0002_college_company_gateguard_tbl_job_tbl_tutor"),
    ]

    operations = [
        migrations.CreateModel(
            name="tbl_student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=15)),
                ("address", models.TextField(blank=True, null=True)),
                ("dob", models.DateField()),
                ("year", models.IntegerField(blank=True, null=True)),
                ("supply", models.CharField(blank=True, max_length=100, null=True)),
                ("batch", models.CharField(blank=True, max_length=100, null=True)),
                ("student_id", models.CharField(max_length=50, unique=True)),
                ("register_number", models.CharField(max_length=50)),
                ("roll_number", models.CharField(max_length=50)),
                ("role", models.CharField(default="student", max_length=100)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="student_images/"
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="adminapp.tbl_course",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="adminapp.tbl_department",
                    ),
                ),
                (
                    "hod",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="adminapp.tbl_hod",
                    ),
                ),
                (
                    "tutor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="adminapp.tbl_tutor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request_date", models.DateField(blank=True, null=True)),
                ("request_time", models.TimeField(blank=True, null=True)),
                ("reason", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[("Urgent", "Urgent"), ("Not Urgent", "Not Urgent")],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Rejected by Tutor", "Rejected by Tutor"),
                            ("Tutor Approved", "Tutor Approved"),
                            ("HOD Rejected", "HOD Rejected"),
                            ("HOD Approved", "HOD Approved"),
                            ("Leaved", "Leaved"),
                            ("Not Leaved", "Not Leaved"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                ("forwarded_to_hod", models.BooleanField(default=False)),
                (
                    "qr_code",
                    models.ImageField(blank=True, null=True, upload_to="qr_codes/"),
                ),
                ("is_leaved", models.BooleanField(default=False)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=campuskeyapi.models.get_current_ist_datetime
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="adminapp.tbl_course",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="adminapp.tbl_department",
                    ),
                ),
                (
                    "hod",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_requests",
                        to="adminapp.tbl_hod",
                    ),
                ),
                (
                    "tutor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_requests",
                        to="adminapp.tbl_tutor",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_requests",
                        to="campuskeyapi.tbl_student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MarkAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(default=campuskeyapi.models.get_current_ist_date),
                ),
                (
                    "time",
                    models.TimeField(default=campuskeyapi.models.get_current_ist_time),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Present", "Present"),
                            ("Absent", "Absent"),
                            ("Not Marked", "Not Marked"),
                        ],
                        default="Not Marked",
                        max_length=15,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="campuskeyapi.tbl_student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resume", models.FileField(upload_to="resumes/")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                            ("Company Reviewed", "Company Reviewed"),
                            ("Company Approved", "Company Approved"),
                            ("Company Rejected", "Company Rejected"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                (
                    "applied_at",
                    models.DateTimeField(
                        default=campuskeyapi.models.get_current_ist_datetime
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="adminapp.tbl_job",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="campuskeyapi.tbl_student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(default=campuskeyapi.models.get_current_ist_date),
                ),
                (
                    "time",
                    models.TimeField(default=campuskeyapi.models.get_current_ist_time),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="campuskeyapi.tbl_student",
                    ),
                ),
            ],
            options={
                "unique_together": {("student", "date")},
            },
        ),
    ]
