# Generated by Django 5.1.7 on 2025-12-23 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="College",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("langitude", models.FloatField()),
                ("lotitude", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("logo", models.ImageField(upload_to="company_logos/")),
                (
                    "description",
                    models.TextField(blank=True, max_length=500, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GateGuard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("guard_id", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("phone", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="guard_photos/"),
                ),
                ("gate_location", models.CharField(max_length=100)),
                ("roles", models.CharField(default="guard", max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Tbl_Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("logo", models.ImageField(upload_to="company_logo/")),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("full-time", "Full-Time"),
                            ("part-time", "Part-Time"),
                        ],
                        default="full-time",
                        max_length=10,
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("place", models.CharField(max_length=255)),
                ("date", models.DateField(auto_now_add=True)),
                ("salary", models.DecimalField(decimal_places=2, max_digits=10)),
                ("responsibilities", models.TextField(max_length=500)),
                ("qualifications", models.TextField(max_length=500)),
                ("vacancy", models.PositiveIntegerField(default=1)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="adminapp.company",
                    ),
                ),
                (
                    "department_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job",
                        to="adminapp.tbl_department",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="tbl_tutor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("tutor_id", models.CharField(max_length=50, unique=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="tutor_images/"),
                ),
                ("roles", models.CharField(default="tutor", max_length=100)),
                ("experience", models.IntegerField(default=0)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "year",
                    models.IntegerField(
                        choices=[
                            (1, "First Year"),
                            (2, "Second Year"),
                            (3, "Third Year"),
                            (4, "Fourth Year"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "batch",
                    models.CharField(
                        default="2025-2029",
                        help_text="Format: YYYY-YYYY",
                        max_length=20,
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tutor_courses",
                        to="adminapp.tbl_course",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tutors",
                        to="adminapp.tbl_department",
                    ),
                ),
                (
                    "hod",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hods",
                        to="adminapp.tbl_hod",
                    ),
                ),
            ],
        ),
    ]
