# Generated by Django 5.2.9 on 2026-01-02 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0003_feestructure"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feestructure",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="adminapp.tbl_course"
            ),
        ),
        migrations.AlterField(
            model_name="feestructure",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="adminapp.tbl_department",
            ),
        ),
    ]
