# Generated by Django 5.2.9 on 2026-01-02 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0004_alter_feestructure_course_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdmissionProcess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step_title", models.CharField(max_length=200)),
                ("step_description", models.TextField()),
                (
                    "order",
                    models.PositiveIntegerField(help_text="Step order (1,2,3...)"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admission_processes",
                        to="adminapp.tbl_course",
                    ),
                ),
            ],
        ),
    ]
