# Generated by Django 5.2.9 on 2026-01-02 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0005_admissionprocess"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="admissionprocess",
            name="course",
        ),
    ]
