# Generated by Django 5.2.9 on 2026-03-02 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_remove_admissionprocess_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_job',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
